-- Generated by roblox-slang. DO NOT MODIFY BY HAND!

local EMBEDDED_TRANSLATIONS = {
	["en"] = {
		["game.menu.about"] = "About",
		["game.menu.achievements"] = "Achievements",
		["game.menu.credits"] = "Credits",
		["game.menu.friends"] = "Friends",
		["game.menu.help"] = "Help",
		["game.menu.leaderboard"] = "Leaderboard",
		["game.menu.play"] = "Play",
		["game.menu.profile"] = "Profile",
		["game.menu.quit"] = "Quit",
		["game.menu.settings"] = "Settings",
		["game.modes.arena"] = "Arena",
		["game.modes.campaign"] = "Campaign",
		["game.modes.coop"] = "Co-op",
		["game.modes.multiplayer"] = "Multiplayer",
		["game.modes.practice"] = "Practice",
		["game.modes.raid"] = "Raid",
		["game.modes.singleplayer"] = "Single Player",
		["game.modes.survival"] = "Survival",
		["game.modes.tutorial"] = "Tutorial",
		["game.modes.versus"] = "Versus",
		["game.notifications.achievementUnlocked"] = "Achievement unlocked: {achievement}",
		["game.notifications.friendRequest"] = "{name} sent you a friend request",
		["game.notifications.levelUp"] = "Level up! You are now level {level}",
		["game.notifications.partyInvite"] = "{name} invited you to a party",
		["game.notifications.questComplete"] = "Quest completed: {quest}",
		["game.notifications.tradeRequest"] = "{name} wants to trade with you",
		["game.status.away"] = "Away",
		["game.status.busy"] = "Busy",
		["game.status.connected"] = "Connected",
		["game.status.connecting"] = "Connecting...",
		["game.status.disconnected"] = "Disconnected",
		["game.status.inGame"] = "In Game",
		["game.status.inLobby"] = "In Lobby",
		["game.status.offline"] = "Offline",
		["game.status.online"] = "Online",
		["game.status.searching"] = "Searching...",
		["inventory.actions.destroy"] = "Destroy",
		["inventory.actions.drop"] = "Drop",
		["inventory.actions.enchant"] = "Enchant",
		["inventory.actions.equip"] = "Equip",
		["inventory.actions.gift"] = "Gift",
		["inventory.actions.repair"] = "Repair",
		["inventory.actions.trade"] = "Trade",
		["inventory.actions.unequip"] = "Unequip",
		["inventory.actions.upgrade"] = "Upgrade",
		["inventory.actions.use"] = "Use",
		["inventory.info.damage"] = "Damage: {damage:int}",
		["inventory.info.defense"] = "Defense: {defense:int}",
		["inventory.info.durability"] = "Durability: {current}/{max}",
		["inventory.info.quantity"] = "Quantity: {quantity:int}",
		["inventory.info.rarity"] = "Rarity: {rarity}",
		["inventory.info.weight"] = "Weight: {weight:fixed(1)}",
		["inventory.tabs.all"] = "All",
		["inventory.tabs.armor"] = "Armor",
		["inventory.tabs.consumables"] = "Consumables",
		["inventory.tabs.materials"] = "Materials",
		["inventory.tabs.pets"] = "Pets",
		["inventory.tabs.quest"] = "Quest Items",
		["inventory.tabs.vehicles"] = "Vehicles",
		["inventory.tabs.weapons"] = "Weapons",
		["settings.categories.accessibility"] = "Accessibility",
		["settings.categories.audio"] = "Audio",
		["settings.categories.controls"] = "Controls",
		["settings.categories.gameplay"] = "Gameplay",
		["settings.categories.general"] = "General",
		["settings.categories.graphics"] = "Graphics",
		["settings.options.brightness"] = "Brightness",
		["settings.options.fov"] = "Field of View",
		["settings.options.fullscreen"] = "Fullscreen",
		["settings.options.invertY"] = "Invert Y-Axis",
		["settings.options.language"] = "Language",
		["settings.options.mouseSensitivity"] = "Mouse Sensitivity",
		["settings.options.musicVolume"] = "Music Volume",
		["settings.options.particles"] = "Particles",
		["settings.options.quality"] = "Graphics Quality",
		["settings.options.sfxVolume"] = "SFX Volume",
		["settings.options.shadows"] = "Shadows",
		["settings.options.volume"] = "Volume",
		["settings.options.vsync"] = "VSync",
		["shop.actions.addToCart"] = "Add to Cart",
		["shop.actions.checkout"] = "Checkout",
		["shop.actions.clearCart"] = "Clear Cart",
		["shop.actions.compare"] = "Compare",
		["shop.actions.preview"] = "Preview",
		["shop.actions.purchase"] = "Purchase",
		["shop.actions.removeFromCart"] = "Remove from Cart",
		["shop.actions.viewCart"] = "View Cart",
		["shop.categories.accessories"] = "Accessories",
		["shop.categories.armor"] = "Armor",
		["shop.categories.bundles"] = "Bundles",
		["shop.categories.consumables"] = "Consumables",
		["shop.categories.emotes"] = "Emotes",
		["shop.categories.equipment"] = "Equipment",
		["shop.categories.featured"] = "Featured",
		["shop.categories.gamepasses"] = "Game Passes",
		["shop.categories.materials"] = "Materials",
		["shop.categories.pets"] = "Pets",
		["shop.categories.potions"] = "Potions",
		["shop.categories.vehicles"] = "Vehicles",
		["shop.categories.weapons"] = "Weapons",
		["shop.messages.cartEmpty"] = "Your cart is empty",
		["shop.messages.insufficientFunds"] = "Insufficient funds",
		["shop.messages.insufficientRobux"] = "Not enough Robux",
		["shop.messages.itemAdded"] = "Item added to cart",
		["shop.messages.itemRemoved"] = "Item removed from cart",
		["shop.messages.purchaseFailed"] = "Purchase failed",
		["shop.messages.purchaseSuccess"] = "Purchase successful!",
		["shop.messages.requiresGamepass"] = "Requires game pass: {gamepass}",
		["social.chat.globalChat"] = "Global Chat",
		["social.chat.mute"] = "Mute",
		["social.chat.report"] = "Report",
		["social.chat.send"] = "Send",
		["social.chat.teamChat"] = "Team Chat",
		["social.chat.unmute"] = "Unmute",
		["social.chat.whisper"] = "Whisper",
		["social.friends.add"] = "Add Friend",
		["social.friends.block"] = "Block",
		["social.friends.invite"] = "Invite to Game",
		["social.friends.offline"] = "Offline Friends",
		["social.friends.online"] = "Online Friends",
		["social.friends.remove"] = "Remove Friend",
		["social.friends.requests"] = "Friend Requests",
		["social.friends.unblock"] = "Unblock",
		["social.party.create"] = "Create Party",
		["social.party.invite"] = "Invite to Party",
		["social.party.join"] = "Join Party",
		["social.party.kick"] = "Kick from Party",
		["social.party.leave"] = "Leave Party",
		["social.party.promote"] = "Promote to Leader",
		["ui.buttons.apply"] = "Apply",
		["ui.buttons.back"] = "Back",
		["ui.buttons.buy"] = "Buy now",
		["ui.buttons.cancel"] = "Cancel",
		["ui.buttons.close"] = "Close",
		["ui.buttons.confirm"] = "Confirm",
		["ui.buttons.create"] = "Create",
		["ui.buttons.delete"] = "Delete",
		["ui.buttons.edit"] = "Edit",
		["ui.buttons.load"] = "Load",
		["ui.buttons.next"] = "Next",
		["ui.buttons.reset"] = "Reset",
		["ui.buttons.save"] = "Save",
		["ui.buttons.sell"] = "Sell",
		["ui.buttons.submit"] = "Submit",
		["ui.labels.coins"] = "Coins",
		["ui.labels.displayName"] = "Display Name",
		["ui.labels.experience"] = "Experience",
		["ui.labels.gems"] = "Gems",
		["ui.labels.health"] = "Health",
		["ui.labels.level"] = "Level",
		["ui.labels.mana"] = "Mana",
		["ui.labels.player"] = "Player",
		["ui.labels.robux"] = "Robux",
		["ui.labels.stamina"] = "Stamina",
		["ui.labels.welcome"] = "Welcome to the game!",
		["ui.messages.error"] = "Error occurred",
		["ui.messages.greeting"] = "Hello, {name}!",
		["ui.messages.itemCount"] = "You have {count} items",
		["ui.messages.items(one)"] = "{count} item",
		["ui.messages.items(other)"] = "{count} items",
		["ui.messages.loading"] = "Loading...",
		["ui.messages.playerJoined"] = "{name} joined the game",
		["ui.messages.playerLeft"] = "{name} left the game",
		["ui.messages.price"] = "Price: ${price:fixed(2)}",
		["ui.messages.saving"] = "Saving...",
		["ui.messages.score"] = "Score: {score:int}",
		["ui.messages.success"] = "Success!",
		["ui.messages.warning"] = "Warning!",
		["ui.tooltips.buyItem"] = "Click to purchase this item",
		["ui.tooltips.equipItem"] = "Click to equip this item",
		["ui.tooltips.sellItem"] = "Click to sell this item",
		["ui.tooltips.unequipItem"] = "Click to unequip this item",
		["ui.tooltips.upgradeItem"] = "Click to upgrade this item",
	},
}

local Translations = {}
Translations.__index = Translations

function Translations.new(locale)
	local self = setmetatable({}, Translations)
	self._locale = locale or "en"
	self._localeChangedCallbacks = {}

	Translations._setupNamespaces(self)
	return self
end

function Translations:setLocale(locale)
	if self._locale == locale then
		return
	end

	local oldLocale = self._locale
	self._locale = locale

	for _, callback in ipairs(self._localeChangedCallbacks) do
		task.spawn(callback, locale, oldLocale)
	end
end

function Translations:getLocale()
	return self._locale
end

function Translations:onLocaleChanged(callback)
	table.insert(self._localeChangedCallbacks, callback)
end

function Translations.detectLocale(player)
	local localeId = player.LocaleId
	if not localeId or localeId == "" then
		return "en"
	end

	local normalized = string.lower(localeId):gsub("_", "-")
	local baseCode = string.match(normalized, "^(%w+)")
	if baseCode == "zh" then
		return normalized
	end
	return baseCode or "en"
end

function Translations.newForPlayer(player)
	local locale = Translations.detectLocale(player)
	return Translations.new(locale)
end

function Translations:game_menu_about()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.menu.about"] or "game.menu.about"
end

function Translations:game_menu_achievements()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.menu.achievements"] or "game.menu.achievements"
end

function Translations:game_menu_credits()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.menu.credits"] or "game.menu.credits"
end

function Translations:game_menu_friends()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.menu.friends"] or "game.menu.friends"
end

function Translations:game_menu_help()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.menu.help"] or "game.menu.help"
end

function Translations:game_menu_leaderboard()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.menu.leaderboard"] or "game.menu.leaderboard"
end

function Translations:game_menu_play()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.menu.play"] or "game.menu.play"
end

function Translations:game_menu_profile()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.menu.profile"] or "game.menu.profile"
end

function Translations:game_menu_quit()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.menu.quit"] or "game.menu.quit"
end

function Translations:game_menu_settings()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.menu.settings"] or "game.menu.settings"
end

function Translations:game_modes_arena()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.modes.arena"] or "game.modes.arena"
end

function Translations:game_modes_campaign()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.modes.campaign"] or "game.modes.campaign"
end

function Translations:game_modes_coop()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.modes.coop"] or "game.modes.coop"
end

function Translations:game_modes_multiplayer()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.modes.multiplayer"] or "game.modes.multiplayer"
end

function Translations:game_modes_practice()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.modes.practice"] or "game.modes.practice"
end

function Translations:game_modes_raid()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.modes.raid"] or "game.modes.raid"
end

function Translations:game_modes_singleplayer()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.modes.singleplayer"] or "game.modes.singleplayer"
end

function Translations:game_modes_survival()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.modes.survival"] or "game.modes.survival"
end

function Translations:game_modes_tutorial()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.modes.tutorial"] or "game.modes.tutorial"
end

function Translations:game_modes_versus()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.modes.versus"] or "game.modes.versus"
end

function Translations:game_notifications_achievementUnlocked(params)
	params = params or {}
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["game.notifications.achievementUnlocked"] or "game.notifications.achievementUnlocked"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:game_notifications_friendRequest(params)
	params = params or {}
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["game.notifications.friendRequest"] or "game.notifications.friendRequest"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:game_notifications_levelUp(params)
	params = params or {}
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["game.notifications.levelUp"] or "game.notifications.levelUp"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:game_notifications_partyInvite(params)
	params = params or {}
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["game.notifications.partyInvite"] or "game.notifications.partyInvite"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:game_notifications_questComplete(params)
	params = params or {}
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["game.notifications.questComplete"] or "game.notifications.questComplete"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:game_notifications_tradeRequest(params)
	params = params or {}
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["game.notifications.tradeRequest"] or "game.notifications.tradeRequest"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:game_status_away()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.status.away"] or "game.status.away"
end

function Translations:game_status_busy()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.status.busy"] or "game.status.busy"
end

function Translations:game_status_connected()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.status.connected"] or "game.status.connected"
end

function Translations:game_status_connecting()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.status.connecting"] or "game.status.connecting"
end

function Translations:game_status_disconnected()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.status.disconnected"] or "game.status.disconnected"
end

function Translations:game_status_inGame()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.status.inGame"] or "game.status.inGame"
end

function Translations:game_status_inLobby()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.status.inLobby"] or "game.status.inLobby"
end

function Translations:game_status_offline()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.status.offline"] or "game.status.offline"
end

function Translations:game_status_online()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.status.online"] or "game.status.online"
end

function Translations:game_status_searching()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["game.status.searching"] or "game.status.searching"
end

function Translations:inventory_actions_destroy()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.actions.destroy"] or "inventory.actions.destroy"
end

function Translations:inventory_actions_drop()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.actions.drop"] or "inventory.actions.drop"
end

function Translations:inventory_actions_enchant()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.actions.enchant"] or "inventory.actions.enchant"
end

function Translations:inventory_actions_equip()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.actions.equip"] or "inventory.actions.equip"
end

function Translations:inventory_actions_gift()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.actions.gift"] or "inventory.actions.gift"
end

function Translations:inventory_actions_repair()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.actions.repair"] or "inventory.actions.repair"
end

function Translations:inventory_actions_trade()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.actions.trade"] or "inventory.actions.trade"
end

function Translations:inventory_actions_unequip()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.actions.unequip"] or "inventory.actions.unequip"
end

function Translations:inventory_actions_upgrade()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.actions.upgrade"] or "inventory.actions.upgrade"
end

function Translations:inventory_actions_use()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.actions.use"] or "inventory.actions.use"
end

function Translations:inventory_info_damage(params)
	params = params or {}
	params.damage = math.floor(tonumber(params.damage) or 0)
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["inventory.info.damage"] or "inventory.info.damage"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:inventory_info_defense(params)
	params = params or {}
	params.defense = math.floor(tonumber(params.defense) or 0)
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["inventory.info.defense"] or "inventory.info.defense"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:inventory_info_durability(params)
	params = params or {}
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["inventory.info.durability"] or "inventory.info.durability"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:inventory_info_quantity(params)
	params = params or {}
	params.quantity = math.floor(tonumber(params.quantity) or 0)
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["inventory.info.quantity"] or "inventory.info.quantity"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:inventory_info_rarity(params)
	params = params or {}
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["inventory.info.rarity"] or "inventory.info.rarity"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:inventory_info_weight(params)
	params = params or {}
	params.weight = string.format("%.1f", tonumber(params.weight) or 0)
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["inventory.info.weight"] or "inventory.info.weight"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:inventory_tabs_all()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.tabs.all"] or "inventory.tabs.all"
end

function Translations:inventory_tabs_armor()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.tabs.armor"] or "inventory.tabs.armor"
end

function Translations:inventory_tabs_consumables()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.tabs.consumables"] or "inventory.tabs.consumables"
end

function Translations:inventory_tabs_materials()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.tabs.materials"] or "inventory.tabs.materials"
end

function Translations:inventory_tabs_pets()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.tabs.pets"] or "inventory.tabs.pets"
end

function Translations:inventory_tabs_quest()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.tabs.quest"] or "inventory.tabs.quest"
end

function Translations:inventory_tabs_vehicles()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.tabs.vehicles"] or "inventory.tabs.vehicles"
end

function Translations:inventory_tabs_weapons()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["inventory.tabs.weapons"] or "inventory.tabs.weapons"
end

function Translations:settings_categories_accessibility()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.categories.accessibility"] or "settings.categories.accessibility"
end

function Translations:settings_categories_audio()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.categories.audio"] or "settings.categories.audio"
end

function Translations:settings_categories_controls()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.categories.controls"] or "settings.categories.controls"
end

function Translations:settings_categories_gameplay()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.categories.gameplay"] or "settings.categories.gameplay"
end

function Translations:settings_categories_general()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.categories.general"] or "settings.categories.general"
end

function Translations:settings_categories_graphics()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.categories.graphics"] or "settings.categories.graphics"
end

function Translations:settings_options_brightness()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.options.brightness"] or "settings.options.brightness"
end

function Translations:settings_options_fov()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.options.fov"] or "settings.options.fov"
end

function Translations:settings_options_fullscreen()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.options.fullscreen"] or "settings.options.fullscreen"
end

function Translations:settings_options_invertY()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.options.invertY"] or "settings.options.invertY"
end

function Translations:settings_options_language()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.options.language"] or "settings.options.language"
end

function Translations:settings_options_mouseSensitivity()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.options.mouseSensitivity"] or "settings.options.mouseSensitivity"
end

function Translations:settings_options_musicVolume()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.options.musicVolume"] or "settings.options.musicVolume"
end

function Translations:settings_options_particles()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.options.particles"] or "settings.options.particles"
end

function Translations:settings_options_quality()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.options.quality"] or "settings.options.quality"
end

function Translations:settings_options_sfxVolume()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.options.sfxVolume"] or "settings.options.sfxVolume"
end

function Translations:settings_options_shadows()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.options.shadows"] or "settings.options.shadows"
end

function Translations:settings_options_volume()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.options.volume"] or "settings.options.volume"
end

function Translations:settings_options_vsync()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["settings.options.vsync"] or "settings.options.vsync"
end

function Translations:shop_actions_addToCart()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.actions.addToCart"] or "shop.actions.addToCart"
end

function Translations:shop_actions_checkout()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.actions.checkout"] or "shop.actions.checkout"
end

function Translations:shop_actions_clearCart()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.actions.clearCart"] or "shop.actions.clearCart"
end

function Translations:shop_actions_compare()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.actions.compare"] or "shop.actions.compare"
end

function Translations:shop_actions_preview()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.actions.preview"] or "shop.actions.preview"
end

function Translations:shop_actions_purchase()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.actions.purchase"] or "shop.actions.purchase"
end

function Translations:shop_actions_removeFromCart()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.actions.removeFromCart"] or "shop.actions.removeFromCart"
end

function Translations:shop_actions_viewCart()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.actions.viewCart"] or "shop.actions.viewCart"
end

function Translations:shop_categories_accessories()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.categories.accessories"] or "shop.categories.accessories"
end

function Translations:shop_categories_armor()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.categories.armor"] or "shop.categories.armor"
end

function Translations:shop_categories_bundles()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.categories.bundles"] or "shop.categories.bundles"
end

function Translations:shop_categories_consumables()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.categories.consumables"] or "shop.categories.consumables"
end

function Translations:shop_categories_emotes()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.categories.emotes"] or "shop.categories.emotes"
end

function Translations:shop_categories_equipment()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.categories.equipment"] or "shop.categories.equipment"
end

function Translations:shop_categories_featured()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.categories.featured"] or "shop.categories.featured"
end

function Translations:shop_categories_gamepasses()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.categories.gamepasses"] or "shop.categories.gamepasses"
end

function Translations:shop_categories_materials()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.categories.materials"] or "shop.categories.materials"
end

function Translations:shop_categories_pets()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.categories.pets"] or "shop.categories.pets"
end

function Translations:shop_categories_potions()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.categories.potions"] or "shop.categories.potions"
end

function Translations:shop_categories_vehicles()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.categories.vehicles"] or "shop.categories.vehicles"
end

function Translations:shop_categories_weapons()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.categories.weapons"] or "shop.categories.weapons"
end

function Translations:shop_messages_cartEmpty()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.messages.cartEmpty"] or "shop.messages.cartEmpty"
end

function Translations:shop_messages_insufficientFunds()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.messages.insufficientFunds"] or "shop.messages.insufficientFunds"
end

function Translations:shop_messages_insufficientRobux()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.messages.insufficientRobux"] or "shop.messages.insufficientRobux"
end

function Translations:shop_messages_itemAdded()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.messages.itemAdded"] or "shop.messages.itemAdded"
end

function Translations:shop_messages_itemRemoved()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.messages.itemRemoved"] or "shop.messages.itemRemoved"
end

function Translations:shop_messages_purchaseFailed()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.messages.purchaseFailed"] or "shop.messages.purchaseFailed"
end

function Translations:shop_messages_purchaseSuccess()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["shop.messages.purchaseSuccess"] or "shop.messages.purchaseSuccess"
end

function Translations:shop_messages_requiresGamepass(params)
	params = params or {}
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["shop.messages.requiresGamepass"] or "shop.messages.requiresGamepass"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:social_chat_globalChat()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.chat.globalChat"] or "social.chat.globalChat"
end

function Translations:social_chat_mute()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.chat.mute"] or "social.chat.mute"
end

function Translations:social_chat_report()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.chat.report"] or "social.chat.report"
end

function Translations:social_chat_send()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.chat.send"] or "social.chat.send"
end

function Translations:social_chat_teamChat()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.chat.teamChat"] or "social.chat.teamChat"
end

function Translations:social_chat_unmute()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.chat.unmute"] or "social.chat.unmute"
end

function Translations:social_chat_whisper()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.chat.whisper"] or "social.chat.whisper"
end

function Translations:social_friends_add()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.friends.add"] or "social.friends.add"
end

function Translations:social_friends_block()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.friends.block"] or "social.friends.block"
end

function Translations:social_friends_invite()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.friends.invite"] or "social.friends.invite"
end

function Translations:social_friends_offline()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.friends.offline"] or "social.friends.offline"
end

function Translations:social_friends_online()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.friends.online"] or "social.friends.online"
end

function Translations:social_friends_remove()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.friends.remove"] or "social.friends.remove"
end

function Translations:social_friends_requests()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.friends.requests"] or "social.friends.requests"
end

function Translations:social_friends_unblock()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.friends.unblock"] or "social.friends.unblock"
end

function Translations:social_party_create()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.party.create"] or "social.party.create"
end

function Translations:social_party_invite()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.party.invite"] or "social.party.invite"
end

function Translations:social_party_join()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.party.join"] or "social.party.join"
end

function Translations:social_party_kick()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.party.kick"] or "social.party.kick"
end

function Translations:social_party_leave()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.party.leave"] or "social.party.leave"
end

function Translations:social_party_promote()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["social.party.promote"] or "social.party.promote"
end

function Translations:ui_buttons_apply()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.apply"] or "ui.buttons.apply"
end

function Translations:ui_buttons_back()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.back"] or "ui.buttons.back"
end

function Translations:ui_buttons_buy()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.buy"] or "ui.buttons.buy"
end

function Translations:ui_buttons_cancel()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.cancel"] or "ui.buttons.cancel"
end

function Translations:ui_buttons_close()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.close"] or "ui.buttons.close"
end

function Translations:ui_buttons_confirm()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.confirm"] or "ui.buttons.confirm"
end

function Translations:ui_buttons_create()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.create"] or "ui.buttons.create"
end

function Translations:ui_buttons_delete()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.delete"] or "ui.buttons.delete"
end

function Translations:ui_buttons_edit()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.edit"] or "ui.buttons.edit"
end

function Translations:ui_buttons_load()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.load"] or "ui.buttons.load"
end

function Translations:ui_buttons_next()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.next"] or "ui.buttons.next"
end

function Translations:ui_buttons_reset()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.reset"] or "ui.buttons.reset"
end

function Translations:ui_buttons_save()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.save"] or "ui.buttons.save"
end

function Translations:ui_buttons_sell()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.sell"] or "ui.buttons.sell"
end

function Translations:ui_buttons_submit()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.submit"] or "ui.buttons.submit"
end

function Translations:ui_labels_coins()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.labels.coins"] or "ui.labels.coins"
end

function Translations:ui_labels_displayName()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.labels.displayName"] or "ui.labels.displayName"
end

function Translations:ui_labels_experience()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.labels.experience"] or "ui.labels.experience"
end

function Translations:ui_labels_gems()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.labels.gems"] or "ui.labels.gems"
end

function Translations:ui_labels_health()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.labels.health"] or "ui.labels.health"
end

function Translations:ui_labels_level()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.labels.level"] or "ui.labels.level"
end

function Translations:ui_labels_mana()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.labels.mana"] or "ui.labels.mana"
end

function Translations:ui_labels_player()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.labels.player"] or "ui.labels.player"
end

function Translations:ui_labels_robux()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.labels.robux"] or "ui.labels.robux"
end

function Translations:ui_labels_stamina()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.labels.stamina"] or "ui.labels.stamina"
end

function Translations:ui_labels_welcome()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.labels.welcome"] or "ui.labels.welcome"
end

function Translations:ui_messages_error()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.messages.error"] or "ui.messages.error"
end

function Translations:ui_messages_greeting(params)
	params = params or {}
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["ui.messages.greeting"] or "ui.messages.greeting"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:ui_messages_itemCount(params)
	params = params or {}
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["ui.messages.itemCount"] or "ui.messages.itemCount"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:ui_messages_loading()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.messages.loading"] or "ui.messages.loading"
end

function Translations:ui_messages_playerJoined(params)
	params = params or {}
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["ui.messages.playerJoined"] or "ui.messages.playerJoined"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:ui_messages_playerLeft(params)
	params = params or {}
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["ui.messages.playerLeft"] or "ui.messages.playerLeft"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:ui_messages_price(params)
	params = params or {}
	params.price = string.format("%.2f", tonumber(params.price) or 0)
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["ui.messages.price"] or "ui.messages.price"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:ui_messages_saving()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.messages.saving"] or "ui.messages.saving"
end

function Translations:ui_messages_score(params)
	params = params or {}
	params.score = math.floor(tonumber(params.score) or 0)
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local template = locale_data["ui.messages.score"] or "ui.messages.score"

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations:ui_messages_success()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.messages.success"] or "ui.messages.success"
end

function Translations:ui_messages_warning()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.messages.warning"] or "ui.messages.warning"
end

function Translations:ui_tooltips_buyItem()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.tooltips.buyItem"] or "ui.tooltips.buyItem"
end

function Translations:ui_tooltips_equipItem()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.tooltips.equipItem"] or "ui.tooltips.equipItem"
end

function Translations:ui_tooltips_sellItem()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.tooltips.sellItem"] or "ui.tooltips.sellItem"
end

function Translations:ui_tooltips_unequipItem()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.tooltips.unequipItem"] or "ui.tooltips.unequipItem"
end

function Translations:ui_tooltips_upgradeItem()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.tooltips.upgradeItem"] or "ui.tooltips.upgradeItem"
end

function Translations:ui_messages_items(count, params)
	params = params or {}
	params.count = count

	local category = "other"

	if self._locale == "en" then
		if count == 1 then
			category = "one"
		end
	elseif self._locale == "ru" or self._locale == "uk" then
		local mod10 = math.abs(count) % 10
		local mod100 = math.abs(count) % 100
		if mod10 == 1 and mod100 ~= 11 then
			category = "one"
		elseif mod10 >= 2 and mod10 <= 4 and (mod100 < 12 or mod100 > 14) then
			category = "few"
		else
			category = "many"
		end
	elseif self._locale == "ar" then
		local absCount = math.abs(count)
		local mod100 = absCount % 100
		if absCount == 0 then
			category = "zero"
		elseif absCount == 1 then
			category = "one"
		elseif absCount == 2 then
			category = "two"
		elseif mod100 >= 3 and mod100 <= 10 then
			category = "few"
		elseif mod100 >= 11 and mod100 <= 99 then
			category = "many"
		end
	end

	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	local key = "ui.messages.items(" .. category .. ")"
	local template = locale_data[key]

	if not template then
		template = locale_data["ui.messages.items(other)"] or key
	end

	local result = template
	for paramKey, value in pairs(params) do
		result = result:gsub("{" .. paramKey .. "}", tostring(value))
	end

	return result
end

function Translations._setupNamespaces(self)
	self.game = {}
	self.inventory = {}
	self.settings = {}
	self.shop = {}
	self.social = {}
	self.ui = {}
	self.game.menu = {}
	self.game.modes = {}
	self.game.notifications = {}
	self.game.status = {}
	self.inventory.actions = {}
	self.inventory.info = {}
	self.inventory.tabs = {}
	self.settings.categories = {}
	self.settings.options = {}
	self.shop.actions = {}
	self.shop.categories = {}
	self.shop.messages = {}
	self.social.chat = {}
	self.social.friends = {}
	self.social.party = {}
	self.ui.buttons = {}
	self.ui.labels = {}
	self.ui.messages = {}
	self.ui.tooltips = {}

	self.game.menu.about = function()
		return self:game_menu_about()
	end
	self.game.menu.achievements = function()
		return self:game_menu_achievements()
	end
	self.game.menu.credits = function()
		return self:game_menu_credits()
	end
	self.game.menu.friends = function()
		return self:game_menu_friends()
	end
	self.game.menu.help = function()
		return self:game_menu_help()
	end
	self.game.menu.leaderboard = function()
		return self:game_menu_leaderboard()
	end
	self.game.menu.play = function()
		return self:game_menu_play()
	end
	self.game.menu.profile = function()
		return self:game_menu_profile()
	end
	self.game.menu.quit = function()
		return self:game_menu_quit()
	end
	self.game.menu.settings = function()
		return self:game_menu_settings()
	end
	self.game.modes.arena = function()
		return self:game_modes_arena()
	end
	self.game.modes.campaign = function()
		return self:game_modes_campaign()
	end
	self.game.modes.coop = function()
		return self:game_modes_coop()
	end
	self.game.modes.multiplayer = function()
		return self:game_modes_multiplayer()
	end
	self.game.modes.practice = function()
		return self:game_modes_practice()
	end
	self.game.modes.raid = function()
		return self:game_modes_raid()
	end
	self.game.modes.singleplayer = function()
		return self:game_modes_singleplayer()
	end
	self.game.modes.survival = function()
		return self:game_modes_survival()
	end
	self.game.modes.tutorial = function()
		return self:game_modes_tutorial()
	end
	self.game.modes.versus = function()
		return self:game_modes_versus()
	end
	self.game.notifications.achievementUnlocked = function(_, ...)
		return self:game_notifications_achievementUnlocked(...)
	end
	self.game.notifications.friendRequest = function(_, ...)
		return self:game_notifications_friendRequest(...)
	end
	self.game.notifications.levelUp = function(_, ...)
		return self:game_notifications_levelUp(...)
	end
	self.game.notifications.partyInvite = function(_, ...)
		return self:game_notifications_partyInvite(...)
	end
	self.game.notifications.questComplete = function(_, ...)
		return self:game_notifications_questComplete(...)
	end
	self.game.notifications.tradeRequest = function(_, ...)
		return self:game_notifications_tradeRequest(...)
	end
	self.game.status.away = function()
		return self:game_status_away()
	end
	self.game.status.busy = function()
		return self:game_status_busy()
	end
	self.game.status.connected = function()
		return self:game_status_connected()
	end
	self.game.status.connecting = function()
		return self:game_status_connecting()
	end
	self.game.status.disconnected = function()
		return self:game_status_disconnected()
	end
	self.game.status.inGame = function()
		return self:game_status_inGame()
	end
	self.game.status.inLobby = function()
		return self:game_status_inLobby()
	end
	self.game.status.offline = function()
		return self:game_status_offline()
	end
	self.game.status.online = function()
		return self:game_status_online()
	end
	self.game.status.searching = function()
		return self:game_status_searching()
	end
	self.inventory.actions.destroy = function()
		return self:inventory_actions_destroy()
	end
	self.inventory.actions.drop = function()
		return self:inventory_actions_drop()
	end
	self.inventory.actions.enchant = function()
		return self:inventory_actions_enchant()
	end
	self.inventory.actions.equip = function()
		return self:inventory_actions_equip()
	end
	self.inventory.actions.gift = function()
		return self:inventory_actions_gift()
	end
	self.inventory.actions.repair = function()
		return self:inventory_actions_repair()
	end
	self.inventory.actions.trade = function()
		return self:inventory_actions_trade()
	end
	self.inventory.actions.unequip = function()
		return self:inventory_actions_unequip()
	end
	self.inventory.actions.upgrade = function()
		return self:inventory_actions_upgrade()
	end
	self.inventory.actions.use = function()
		return self:inventory_actions_use()
	end
	self.inventory.info.damage = function(_, ...)
		return self:inventory_info_damage(...)
	end
	self.inventory.info.defense = function(_, ...)
		return self:inventory_info_defense(...)
	end
	self.inventory.info.durability = function(_, ...)
		return self:inventory_info_durability(...)
	end
	self.inventory.info.quantity = function(_, ...)
		return self:inventory_info_quantity(...)
	end
	self.inventory.info.rarity = function(_, ...)
		return self:inventory_info_rarity(...)
	end
	self.inventory.info.weight = function(_, ...)
		return self:inventory_info_weight(...)
	end
	self.inventory.tabs.all = function()
		return self:inventory_tabs_all()
	end
	self.inventory.tabs.armor = function()
		return self:inventory_tabs_armor()
	end
	self.inventory.tabs.consumables = function()
		return self:inventory_tabs_consumables()
	end
	self.inventory.tabs.materials = function()
		return self:inventory_tabs_materials()
	end
	self.inventory.tabs.pets = function()
		return self:inventory_tabs_pets()
	end
	self.inventory.tabs.quest = function()
		return self:inventory_tabs_quest()
	end
	self.inventory.tabs.vehicles = function()
		return self:inventory_tabs_vehicles()
	end
	self.inventory.tabs.weapons = function()
		return self:inventory_tabs_weapons()
	end
	self.settings.categories.accessibility = function()
		return self:settings_categories_accessibility()
	end
	self.settings.categories.audio = function()
		return self:settings_categories_audio()
	end
	self.settings.categories.controls = function()
		return self:settings_categories_controls()
	end
	self.settings.categories.gameplay = function()
		return self:settings_categories_gameplay()
	end
	self.settings.categories.general = function()
		return self:settings_categories_general()
	end
	self.settings.categories.graphics = function()
		return self:settings_categories_graphics()
	end
	self.settings.options.brightness = function()
		return self:settings_options_brightness()
	end
	self.settings.options.fov = function()
		return self:settings_options_fov()
	end
	self.settings.options.fullscreen = function()
		return self:settings_options_fullscreen()
	end
	self.settings.options.invertY = function()
		return self:settings_options_invertY()
	end
	self.settings.options.language = function()
		return self:settings_options_language()
	end
	self.settings.options.mouseSensitivity = function()
		return self:settings_options_mouseSensitivity()
	end
	self.settings.options.musicVolume = function()
		return self:settings_options_musicVolume()
	end
	self.settings.options.particles = function()
		return self:settings_options_particles()
	end
	self.settings.options.quality = function()
		return self:settings_options_quality()
	end
	self.settings.options.sfxVolume = function()
		return self:settings_options_sfxVolume()
	end
	self.settings.options.shadows = function()
		return self:settings_options_shadows()
	end
	self.settings.options.volume = function()
		return self:settings_options_volume()
	end
	self.settings.options.vsync = function()
		return self:settings_options_vsync()
	end
	self.shop.actions.addToCart = function()
		return self:shop_actions_addToCart()
	end
	self.shop.actions.checkout = function()
		return self:shop_actions_checkout()
	end
	self.shop.actions.clearCart = function()
		return self:shop_actions_clearCart()
	end
	self.shop.actions.compare = function()
		return self:shop_actions_compare()
	end
	self.shop.actions.preview = function()
		return self:shop_actions_preview()
	end
	self.shop.actions.purchase = function()
		return self:shop_actions_purchase()
	end
	self.shop.actions.removeFromCart = function()
		return self:shop_actions_removeFromCart()
	end
	self.shop.actions.viewCart = function()
		return self:shop_actions_viewCart()
	end
	self.shop.categories.accessories = function()
		return self:shop_categories_accessories()
	end
	self.shop.categories.armor = function()
		return self:shop_categories_armor()
	end
	self.shop.categories.bundles = function()
		return self:shop_categories_bundles()
	end
	self.shop.categories.consumables = function()
		return self:shop_categories_consumables()
	end
	self.shop.categories.emotes = function()
		return self:shop_categories_emotes()
	end
	self.shop.categories.equipment = function()
		return self:shop_categories_equipment()
	end
	self.shop.categories.featured = function()
		return self:shop_categories_featured()
	end
	self.shop.categories.gamepasses = function()
		return self:shop_categories_gamepasses()
	end
	self.shop.categories.materials = function()
		return self:shop_categories_materials()
	end
	self.shop.categories.pets = function()
		return self:shop_categories_pets()
	end
	self.shop.categories.potions = function()
		return self:shop_categories_potions()
	end
	self.shop.categories.vehicles = function()
		return self:shop_categories_vehicles()
	end
	self.shop.categories.weapons = function()
		return self:shop_categories_weapons()
	end
	self.shop.messages.cartEmpty = function()
		return self:shop_messages_cartEmpty()
	end
	self.shop.messages.insufficientFunds = function()
		return self:shop_messages_insufficientFunds()
	end
	self.shop.messages.insufficientRobux = function()
		return self:shop_messages_insufficientRobux()
	end
	self.shop.messages.itemAdded = function()
		return self:shop_messages_itemAdded()
	end
	self.shop.messages.itemRemoved = function()
		return self:shop_messages_itemRemoved()
	end
	self.shop.messages.purchaseFailed = function()
		return self:shop_messages_purchaseFailed()
	end
	self.shop.messages.purchaseSuccess = function()
		return self:shop_messages_purchaseSuccess()
	end
	self.shop.messages.requiresGamepass = function(_, ...)
		return self:shop_messages_requiresGamepass(...)
	end
	self.social.chat.globalChat = function()
		return self:social_chat_globalChat()
	end
	self.social.chat.mute = function()
		return self:social_chat_mute()
	end
	self.social.chat.report = function()
		return self:social_chat_report()
	end
	self.social.chat.send = function()
		return self:social_chat_send()
	end
	self.social.chat.teamChat = function()
		return self:social_chat_teamChat()
	end
	self.social.chat.unmute = function()
		return self:social_chat_unmute()
	end
	self.social.chat.whisper = function()
		return self:social_chat_whisper()
	end
	self.social.friends.add = function()
		return self:social_friends_add()
	end
	self.social.friends.block = function()
		return self:social_friends_block()
	end
	self.social.friends.invite = function()
		return self:social_friends_invite()
	end
	self.social.friends.offline = function()
		return self:social_friends_offline()
	end
	self.social.friends.online = function()
		return self:social_friends_online()
	end
	self.social.friends.remove = function()
		return self:social_friends_remove()
	end
	self.social.friends.requests = function()
		return self:social_friends_requests()
	end
	self.social.friends.unblock = function()
		return self:social_friends_unblock()
	end
	self.social.party.create = function()
		return self:social_party_create()
	end
	self.social.party.invite = function()
		return self:social_party_invite()
	end
	self.social.party.join = function()
		return self:social_party_join()
	end
	self.social.party.kick = function()
		return self:social_party_kick()
	end
	self.social.party.leave = function()
		return self:social_party_leave()
	end
	self.social.party.promote = function()
		return self:social_party_promote()
	end
	self.ui.buttons.apply = function()
		return self:ui_buttons_apply()
	end
	self.ui.buttons.back = function()
		return self:ui_buttons_back()
	end
	self.ui.buttons.buy = function()
		return self:ui_buttons_buy()
	end
	self.ui.buttons.cancel = function()
		return self:ui_buttons_cancel()
	end
	self.ui.buttons.close = function()
		return self:ui_buttons_close()
	end
	self.ui.buttons.confirm = function()
		return self:ui_buttons_confirm()
	end
	self.ui.buttons.create = function()
		return self:ui_buttons_create()
	end
	self.ui.buttons.delete = function()
		return self:ui_buttons_delete()
	end
	self.ui.buttons.edit = function()
		return self:ui_buttons_edit()
	end
	self.ui.buttons.load = function()
		return self:ui_buttons_load()
	end
	self.ui.buttons.next = function()
		return self:ui_buttons_next()
	end
	self.ui.buttons.reset = function()
		return self:ui_buttons_reset()
	end
	self.ui.buttons.save = function()
		return self:ui_buttons_save()
	end
	self.ui.buttons.sell = function()
		return self:ui_buttons_sell()
	end
	self.ui.buttons.submit = function()
		return self:ui_buttons_submit()
	end
	self.ui.labels.coins = function()
		return self:ui_labels_coins()
	end
	self.ui.labels.displayName = function()
		return self:ui_labels_displayName()
	end
	self.ui.labels.experience = function()
		return self:ui_labels_experience()
	end
	self.ui.labels.gems = function()
		return self:ui_labels_gems()
	end
	self.ui.labels.health = function()
		return self:ui_labels_health()
	end
	self.ui.labels.level = function()
		return self:ui_labels_level()
	end
	self.ui.labels.mana = function()
		return self:ui_labels_mana()
	end
	self.ui.labels.player = function()
		return self:ui_labels_player()
	end
	self.ui.labels.robux = function()
		return self:ui_labels_robux()
	end
	self.ui.labels.stamina = function()
		return self:ui_labels_stamina()
	end
	self.ui.labels.welcome = function()
		return self:ui_labels_welcome()
	end
	self.ui.messages.error = function()
		return self:ui_messages_error()
	end
	self.ui.messages.greeting = function(_, ...)
		return self:ui_messages_greeting(...)
	end
	self.ui.messages.itemCount = function(_, ...)
		return self:ui_messages_itemCount(...)
	end
	self.ui.messages.loading = function()
		return self:ui_messages_loading()
	end
	self.ui.messages.playerJoined = function(_, ...)
		return self:ui_messages_playerJoined(...)
	end
	self.ui.messages.playerLeft = function(_, ...)
		return self:ui_messages_playerLeft(...)
	end
	self.ui.messages.price = function(_, ...)
		return self:ui_messages_price(...)
	end
	self.ui.messages.saving = function()
		return self:ui_messages_saving()
	end
	self.ui.messages.score = function(_, ...)
		return self:ui_messages_score(...)
	end
	self.ui.messages.success = function()
		return self:ui_messages_success()
	end
	self.ui.messages.warning = function()
		return self:ui_messages_warning()
	end
	self.ui.tooltips.buyItem = function()
		return self:ui_tooltips_buyItem()
	end
	self.ui.tooltips.equipItem = function()
		return self:ui_tooltips_equipItem()
	end
	self.ui.tooltips.sellItem = function()
		return self:ui_tooltips_sellItem()
	end
	self.ui.tooltips.unequipItem = function()
		return self:ui_tooltips_unequipItem()
	end
	self.ui.tooltips.upgradeItem = function()
		return self:ui_tooltips_upgradeItem()
	end
	self.ui.messages.items = function(_, ...)
		return self:ui_messages_items(...)
	end
end

return Translations
