-- Generated by roblox-slang. DO NOT MODIFY BY HAND!

local EMBEDDED_TRANSLATIONS = {
    ["en"] = {
        ["game.menu.about"] = "About",
        ["game.menu.achievements"] = "Achievements",
        ["game.menu.credits"] = "Credits",
        ["game.menu.friends"] = "Friends",
        ["game.menu.help"] = "Help",
        ["game.menu.leaderboard"] = "Leaderboard",
        ["game.menu.play"] = "Play",
        ["game.menu.profile"] = "Profile",
        ["game.menu.quit"] = "Quit",
        ["game.menu.settings"] = "Settings",
        ["game.modes.arena"] = "Arena",
        ["game.modes.campaign"] = "Campaign",
        ["game.modes.coop"] = "Co-op",
        ["game.modes.multiplayer"] = "Multiplayer",
        ["game.modes.practice"] = "Practice",
        ["game.modes.raid"] = "Raid",
        ["game.modes.singleplayer"] = "Single Player",
        ["game.modes.survival"] = "Survival",
        ["game.modes.tutorial"] = "Tutorial",
        ["game.modes.versus"] = "Versus",
        ["game.notifications.achievementUnlocked"] = "Achievement unlocked: {achievement}",
        ["game.notifications.friendRequest"] = "{name} sent you a friend request",
        ["game.notifications.levelUp"] = "Level up! You are now level {level}",
        ["game.notifications.partyInvite"] = "{name} invited you to a party",
        ["game.notifications.questComplete"] = "Quest completed: {quest}",
        ["game.notifications.tradeRequest"] = "{name} wants to trade with you",
        ["game.status.away"] = "Away",
        ["game.status.busy"] = "Busy",
        ["game.status.connected"] = "Connected",
        ["game.status.connecting"] = "Connecting...",
        ["game.status.disconnected"] = "Disconnected",
        ["game.status.inGame"] = "In Game",
        ["game.status.inLobby"] = "In Lobby",
        ["game.status.offline"] = "Offline",
        ["game.status.online"] = "Online",
        ["game.status.searching"] = "Searching...",
        ["inventory.actions.destroy"] = "Destroy",
        ["inventory.actions.drop"] = "Drop",
        ["inventory.actions.enchant"] = "Enchant",
        ["inventory.actions.equip"] = "Equip",
        ["inventory.actions.gift"] = "Gift",
        ["inventory.actions.repair"] = "Repair",
        ["inventory.actions.trade"] = "Trade",
        ["inventory.actions.unequip"] = "Unequip",
        ["inventory.actions.upgrade"] = "Upgrade",
        ["inventory.actions.use"] = "Use",
        ["inventory.info.damage"] = "Damage: {damage:int}",
        ["inventory.info.defense"] = "Defense: {defense:int}",
        ["inventory.info.durability"] = "Durability: {current}/{max}",
        ["inventory.info.quantity"] = "Quantity: {quantity:int}",
        ["inventory.info.rarity"] = "Rarity: {rarity}",
        ["inventory.info.weight"] = "Weight: {weight:fixed(1)}",
        ["inventory.tabs.all"] = "All",
        ["inventory.tabs.armor"] = "Armor",
        ["inventory.tabs.consumables"] = "Consumables",
        ["inventory.tabs.materials"] = "Materials",
        ["inventory.tabs.pets"] = "Pets",
        ["inventory.tabs.quest"] = "Quest Items",
        ["inventory.tabs.vehicles"] = "Vehicles",
        ["inventory.tabs.weapons"] = "Weapons",
        ["settings.categories.accessibility"] = "Accessibility",
        ["settings.categories.audio"] = "Audio",
        ["settings.categories.controls"] = "Controls",
        ["settings.categories.gameplay"] = "Gameplay",
        ["settings.categories.general"] = "General",
        ["settings.categories.graphics"] = "Graphics",
        ["settings.options.brightness"] = "Brightness",
        ["settings.options.fov"] = "Field of View",
        ["settings.options.fullscreen"] = "Fullscreen",
        ["settings.options.invertY"] = "Invert Y-Axis",
        ["settings.options.language"] = "Language",
        ["settings.options.mouseSensitivity"] = "Mouse Sensitivity",
        ["settings.options.musicVolume"] = "Music Volume",
        ["settings.options.particles"] = "Particles",
        ["settings.options.quality"] = "Graphics Quality",
        ["settings.options.sfxVolume"] = "SFX Volume",
        ["settings.options.shadows"] = "Shadows",
        ["settings.options.volume"] = "Volume",
        ["settings.options.vsync"] = "VSync",
        ["shop.actions.addToCart"] = "Add to Cart",
        ["shop.actions.checkout"] = "Checkout",
        ["shop.actions.clearCart"] = "Clear Cart",
        ["shop.actions.compare"] = "Compare",
        ["shop.actions.preview"] = "Preview",
        ["shop.actions.purchase"] = "Purchase",
        ["shop.actions.removeFromCart"] = "Remove from Cart",
        ["shop.actions.viewCart"] = "View Cart",
        ["shop.categories.accessories"] = "Accessories",
        ["shop.categories.armor"] = "Armor",
        ["shop.categories.bundles"] = "Bundles",
        ["shop.categories.consumables"] = "Consumables",
        ["shop.categories.emotes"] = "Emotes",
        ["shop.categories.equipment"] = "Equipment",
        ["shop.categories.featured"] = "Featured",
        ["shop.categories.gamepasses"] = "Game Passes",
        ["shop.categories.materials"] = "Materials",
        ["shop.categories.pets"] = "Pets",
        ["shop.categories.potions"] = "Potions",
        ["shop.categories.vehicles"] = "Vehicles",
        ["shop.categories.weapons"] = "Weapons",
        ["shop.messages.cartEmpty"] = "Your cart is empty",
        ["shop.messages.insufficientFunds"] = "Insufficient funds",
        ["shop.messages.insufficientRobux"] = "Not enough Robux",
        ["shop.messages.itemAdded"] = "Item added to cart",
        ["shop.messages.itemRemoved"] = "Item removed from cart",
        ["shop.messages.purchaseFailed"] = "Purchase failed",
        ["shop.messages.purchaseSuccess"] = "Purchase successful!",
        ["shop.messages.requiresGamepass"] = "Requires game pass: {gamepass}",
        ["social.chat.globalChat"] = "Global Chat",
        ["social.chat.mute"] = "Mute",
        ["social.chat.report"] = "Report",
        ["social.chat.send"] = "Send",
        ["social.chat.teamChat"] = "Team Chat",
        ["social.chat.unmute"] = "Unmute",
        ["social.chat.whisper"] = "Whisper",
        ["social.friends.add"] = "Add Friend",
        ["social.friends.block"] = "Block",
        ["social.friends.invite"] = "Invite to Game",
        ["social.friends.offline"] = "Offline Friends",
        ["social.friends.online"] = "Online Friends",
        ["social.friends.remove"] = "Remove Friend",
        ["social.friends.requests"] = "Friend Requests",
        ["social.friends.unblock"] = "Unblock",
        ["social.party.create"] = "Create Party",
        ["social.party.invite"] = "Invite to Party",
        ["social.party.join"] = "Join Party",
        ["social.party.kick"] = "Kick from Party",
        ["social.party.leave"] = "Leave Party",
        ["social.party.promote"] = "Promote to Leader",
        ["ui.buttons.apply"] = "Apply",
        ["ui.buttons.back"] = "Back",
        ["ui.buttons.buy"] = "Buy now",
        ["ui.buttons.cancel"] = "Cancel",
        ["ui.buttons.close"] = "Close",
        ["ui.buttons.confirm"] = "Confirm",
        ["ui.buttons.create"] = "Create",
        ["ui.buttons.delete"] = "Delete",
        ["ui.buttons.edit"] = "Edit",
        ["ui.buttons.load"] = "Load",
        ["ui.buttons.next"] = "Next",
        ["ui.buttons.reset"] = "Reset",
        ["ui.buttons.save"] = "Save",
        ["ui.buttons.sell"] = "Sell",
        ["ui.buttons.submit"] = "Submit",
        ["ui.labels.coins"] = "Coins",
        ["ui.labels.displayName"] = "Display Name",
        ["ui.labels.experience"] = "Experience",
        ["ui.labels.gems"] = "Gems",
        ["ui.labels.health"] = "Health",
        ["ui.labels.level"] = "Level",
        ["ui.labels.mana"] = "Mana",
        ["ui.labels.player"] = "Player",
        ["ui.labels.robux"] = "Robux",
        ["ui.labels.stamina"] = "Stamina",
        ["ui.labels.welcome"] = "Welcome to the game!",
        ["ui.messages.error"] = "Error occurred",
        ["ui.messages.greeting"] = "Hello, {name}!",
        ["ui.messages.itemCount"] = "You have {count} items",
        ["ui.messages.items(one)"] = "{count} item",
        ["ui.messages.items(other)"] = "{count} items",
        ["ui.messages.loading"] = "Loading...",
        ["ui.messages.playerJoined"] = "{name} joined the game",
        ["ui.messages.playerLeft"] = "{name} left the game",
        ["ui.messages.price"] = "Price: ${price:fixed(2)}",
        ["ui.messages.saving"] = "Saving...",
        ["ui.messages.score"] = "Score: {score:int}",
        ["ui.messages.success"] = "Success!",
        ["ui.messages.warning"] = "Warning!",
        ["ui.tooltips.buyItem"] = "Click to purchase this item",
        ["ui.tooltips.equipItem"] = "Click to equip this item",
        ["ui.tooltips.sellItem"] = "Click to sell this item",
        ["ui.tooltips.unequipItem"] = "Click to unequip this item",
        ["ui.tooltips.upgradeItem"] = "Click to upgrade this item",
    },
}

local Translations = {}
Translations.__index = Translations

function Translations.new(locale)
    local self = setmetatable({}, Translations)
    self._locale = locale or "en"
    self._localeChangedCallbacks = {}
    
    return self
end

function Translations:setLocale(locale)
    if self._locale == locale then
        return
    end
    
    local oldLocale = self._locale
    self._locale = locale
    
    -- Fire locale changed callbacks
    for _, callback in ipairs(self._localeChangedCallbacks) do
        task.spawn(callback, locale, oldLocale)
    end
end

function Translations:getLocale()
    return self._locale
end

function Translations:onLocaleChanged(callback)
    table.insert(self._localeChangedCallbacks, callback)
end

function Translations:game_menu_about()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.menu.about"] or "game.menu.about"
end

function Translations:game_menu_achievements()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.menu.achievements"] or "game.menu.achievements"
end

function Translations:game_menu_credits()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.menu.credits"] or "game.menu.credits"
end

function Translations:game_menu_friends()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.menu.friends"] or "game.menu.friends"
end

function Translations:game_menu_help()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.menu.help"] or "game.menu.help"
end

function Translations:game_menu_leaderboard()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.menu.leaderboard"] or "game.menu.leaderboard"
end

function Translations:game_menu_play()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.menu.play"] or "game.menu.play"
end

function Translations:game_menu_profile()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.menu.profile"] or "game.menu.profile"
end

function Translations:game_menu_quit()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.menu.quit"] or "game.menu.quit"
end

function Translations:game_menu_settings()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.menu.settings"] or "game.menu.settings"
end

function Translations:game_modes_arena()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.modes.arena"] or "game.modes.arena"
end

function Translations:game_modes_campaign()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.modes.campaign"] or "game.modes.campaign"
end

function Translations:game_modes_coop()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.modes.coop"] or "game.modes.coop"
end

function Translations:game_modes_multiplayer()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.modes.multiplayer"] or "game.modes.multiplayer"
end

function Translations:game_modes_practice()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.modes.practice"] or "game.modes.practice"
end

function Translations:game_modes_raid()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.modes.raid"] or "game.modes.raid"
end

function Translations:game_modes_singleplayer()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.modes.singleplayer"] or "game.modes.singleplayer"
end

function Translations:game_modes_survival()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.modes.survival"] or "game.modes.survival"
end

function Translations:game_modes_tutorial()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.modes.tutorial"] or "game.modes.tutorial"
end

function Translations:game_modes_versus()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.modes.versus"] or "game.modes.versus"
end

function Translations:game_notifications_achievementUnlocked(params)
    params = params or {}
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["game.notifications.achievementUnlocked"] or "game.notifications.achievementUnlocked"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:game_notifications_friendRequest(params)
    params = params or {}
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["game.notifications.friendRequest"] or "game.notifications.friendRequest"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:game_notifications_levelUp(params)
    params = params or {}
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["game.notifications.levelUp"] or "game.notifications.levelUp"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:game_notifications_partyInvite(params)
    params = params or {}
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["game.notifications.partyInvite"] or "game.notifications.partyInvite"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:game_notifications_questComplete(params)
    params = params or {}
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["game.notifications.questComplete"] or "game.notifications.questComplete"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:game_notifications_tradeRequest(params)
    params = params or {}
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["game.notifications.tradeRequest"] or "game.notifications.tradeRequest"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:game_status_away()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.status.away"] or "game.status.away"
end

function Translations:game_status_busy()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.status.busy"] or "game.status.busy"
end

function Translations:game_status_connected()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.status.connected"] or "game.status.connected"
end

function Translations:game_status_connecting()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.status.connecting"] or "game.status.connecting"
end

function Translations:game_status_disconnected()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.status.disconnected"] or "game.status.disconnected"
end

function Translations:game_status_inGame()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.status.inGame"] or "game.status.inGame"
end

function Translations:game_status_inLobby()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.status.inLobby"] or "game.status.inLobby"
end

function Translations:game_status_offline()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.status.offline"] or "game.status.offline"
end

function Translations:game_status_online()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.status.online"] or "game.status.online"
end

function Translations:game_status_searching()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["game.status.searching"] or "game.status.searching"
end

function Translations:inventory_actions_destroy()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.actions.destroy"] or "inventory.actions.destroy"
end

function Translations:inventory_actions_drop()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.actions.drop"] or "inventory.actions.drop"
end

function Translations:inventory_actions_enchant()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.actions.enchant"] or "inventory.actions.enchant"
end

function Translations:inventory_actions_equip()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.actions.equip"] or "inventory.actions.equip"
end

function Translations:inventory_actions_gift()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.actions.gift"] or "inventory.actions.gift"
end

function Translations:inventory_actions_repair()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.actions.repair"] or "inventory.actions.repair"
end

function Translations:inventory_actions_trade()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.actions.trade"] or "inventory.actions.trade"
end

function Translations:inventory_actions_unequip()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.actions.unequip"] or "inventory.actions.unequip"
end

function Translations:inventory_actions_upgrade()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.actions.upgrade"] or "inventory.actions.upgrade"
end

function Translations:inventory_actions_use()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.actions.use"] or "inventory.actions.use"
end

function Translations:inventory_info_damage(params)
    params = params or {}
    params.damage = math.floor(tonumber(params.damage) or 0)
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["inventory.info.damage"] or "inventory.info.damage"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:inventory_info_defense(params)
    params = params or {}
    params.defense = math.floor(tonumber(params.defense) or 0)
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["inventory.info.defense"] or "inventory.info.defense"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:inventory_info_durability(params)
    params = params or {}
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["inventory.info.durability"] or "inventory.info.durability"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:inventory_info_quantity(params)
    params = params or {}
    params.quantity = math.floor(tonumber(params.quantity) or 0)
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["inventory.info.quantity"] or "inventory.info.quantity"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:inventory_info_rarity(params)
    params = params or {}
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["inventory.info.rarity"] or "inventory.info.rarity"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:inventory_info_weight(params)
    params = params or {}
    params.weight = string.format("%.1f", tonumber(params.weight) or 0)
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["inventory.info.weight"] or "inventory.info.weight"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:inventory_tabs_all()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.tabs.all"] or "inventory.tabs.all"
end

function Translations:inventory_tabs_armor()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.tabs.armor"] or "inventory.tabs.armor"
end

function Translations:inventory_tabs_consumables()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.tabs.consumables"] or "inventory.tabs.consumables"
end

function Translations:inventory_tabs_materials()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.tabs.materials"] or "inventory.tabs.materials"
end

function Translations:inventory_tabs_pets()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.tabs.pets"] or "inventory.tabs.pets"
end

function Translations:inventory_tabs_quest()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.tabs.quest"] or "inventory.tabs.quest"
end

function Translations:inventory_tabs_vehicles()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.tabs.vehicles"] or "inventory.tabs.vehicles"
end

function Translations:inventory_tabs_weapons()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["inventory.tabs.weapons"] or "inventory.tabs.weapons"
end

function Translations:settings_categories_accessibility()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.categories.accessibility"] or "settings.categories.accessibility"
end

function Translations:settings_categories_audio()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.categories.audio"] or "settings.categories.audio"
end

function Translations:settings_categories_controls()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.categories.controls"] or "settings.categories.controls"
end

function Translations:settings_categories_gameplay()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.categories.gameplay"] or "settings.categories.gameplay"
end

function Translations:settings_categories_general()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.categories.general"] or "settings.categories.general"
end

function Translations:settings_categories_graphics()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.categories.graphics"] or "settings.categories.graphics"
end

function Translations:settings_options_brightness()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.options.brightness"] or "settings.options.brightness"
end

function Translations:settings_options_fov()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.options.fov"] or "settings.options.fov"
end

function Translations:settings_options_fullscreen()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.options.fullscreen"] or "settings.options.fullscreen"
end

function Translations:settings_options_invertY()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.options.invertY"] or "settings.options.invertY"
end

function Translations:settings_options_language()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.options.language"] or "settings.options.language"
end

function Translations:settings_options_mouseSensitivity()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.options.mouseSensitivity"] or "settings.options.mouseSensitivity"
end

function Translations:settings_options_musicVolume()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.options.musicVolume"] or "settings.options.musicVolume"
end

function Translations:settings_options_particles()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.options.particles"] or "settings.options.particles"
end

function Translations:settings_options_quality()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.options.quality"] or "settings.options.quality"
end

function Translations:settings_options_sfxVolume()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.options.sfxVolume"] or "settings.options.sfxVolume"
end

function Translations:settings_options_shadows()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.options.shadows"] or "settings.options.shadows"
end

function Translations:settings_options_volume()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.options.volume"] or "settings.options.volume"
end

function Translations:settings_options_vsync()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["settings.options.vsync"] or "settings.options.vsync"
end

function Translations:shop_actions_addToCart()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.actions.addToCart"] or "shop.actions.addToCart"
end

function Translations:shop_actions_checkout()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.actions.checkout"] or "shop.actions.checkout"
end

function Translations:shop_actions_clearCart()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.actions.clearCart"] or "shop.actions.clearCart"
end

function Translations:shop_actions_compare()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.actions.compare"] or "shop.actions.compare"
end

function Translations:shop_actions_preview()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.actions.preview"] or "shop.actions.preview"
end

function Translations:shop_actions_purchase()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.actions.purchase"] or "shop.actions.purchase"
end

function Translations:shop_actions_removeFromCart()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.actions.removeFromCart"] or "shop.actions.removeFromCart"
end

function Translations:shop_actions_viewCart()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.actions.viewCart"] or "shop.actions.viewCart"
end

function Translations:shop_categories_accessories()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.categories.accessories"] or "shop.categories.accessories"
end

function Translations:shop_categories_armor()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.categories.armor"] or "shop.categories.armor"
end

function Translations:shop_categories_bundles()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.categories.bundles"] or "shop.categories.bundles"
end

function Translations:shop_categories_consumables()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.categories.consumables"] or "shop.categories.consumables"
end

function Translations:shop_categories_emotes()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.categories.emotes"] or "shop.categories.emotes"
end

function Translations:shop_categories_equipment()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.categories.equipment"] or "shop.categories.equipment"
end

function Translations:shop_categories_featured()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.categories.featured"] or "shop.categories.featured"
end

function Translations:shop_categories_gamepasses()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.categories.gamepasses"] or "shop.categories.gamepasses"
end

function Translations:shop_categories_materials()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.categories.materials"] or "shop.categories.materials"
end

function Translations:shop_categories_pets()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.categories.pets"] or "shop.categories.pets"
end

function Translations:shop_categories_potions()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.categories.potions"] or "shop.categories.potions"
end

function Translations:shop_categories_vehicles()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.categories.vehicles"] or "shop.categories.vehicles"
end

function Translations:shop_categories_weapons()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.categories.weapons"] or "shop.categories.weapons"
end

function Translations:shop_messages_cartEmpty()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.messages.cartEmpty"] or "shop.messages.cartEmpty"
end

function Translations:shop_messages_insufficientFunds()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.messages.insufficientFunds"] or "shop.messages.insufficientFunds"
end

function Translations:shop_messages_insufficientRobux()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.messages.insufficientRobux"] or "shop.messages.insufficientRobux"
end

function Translations:shop_messages_itemAdded()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.messages.itemAdded"] or "shop.messages.itemAdded"
end

function Translations:shop_messages_itemRemoved()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.messages.itemRemoved"] or "shop.messages.itemRemoved"
end

function Translations:shop_messages_purchaseFailed()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.messages.purchaseFailed"] or "shop.messages.purchaseFailed"
end

function Translations:shop_messages_purchaseSuccess()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["shop.messages.purchaseSuccess"] or "shop.messages.purchaseSuccess"
end

function Translations:shop_messages_requiresGamepass(params)
    params = params or {}
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["shop.messages.requiresGamepass"] or "shop.messages.requiresGamepass"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:social_chat_globalChat()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.chat.globalChat"] or "social.chat.globalChat"
end

function Translations:social_chat_mute()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.chat.mute"] or "social.chat.mute"
end

function Translations:social_chat_report()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.chat.report"] or "social.chat.report"
end

function Translations:social_chat_send()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.chat.send"] or "social.chat.send"
end

function Translations:social_chat_teamChat()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.chat.teamChat"] or "social.chat.teamChat"
end

function Translations:social_chat_unmute()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.chat.unmute"] or "social.chat.unmute"
end

function Translations:social_chat_whisper()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.chat.whisper"] or "social.chat.whisper"
end

function Translations:social_friends_add()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.friends.add"] or "social.friends.add"
end

function Translations:social_friends_block()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.friends.block"] or "social.friends.block"
end

function Translations:social_friends_invite()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.friends.invite"] or "social.friends.invite"
end

function Translations:social_friends_offline()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.friends.offline"] or "social.friends.offline"
end

function Translations:social_friends_online()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.friends.online"] or "social.friends.online"
end

function Translations:social_friends_remove()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.friends.remove"] or "social.friends.remove"
end

function Translations:social_friends_requests()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.friends.requests"] or "social.friends.requests"
end

function Translations:social_friends_unblock()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.friends.unblock"] or "social.friends.unblock"
end

function Translations:social_party_create()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.party.create"] or "social.party.create"
end

function Translations:social_party_invite()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.party.invite"] or "social.party.invite"
end

function Translations:social_party_join()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.party.join"] or "social.party.join"
end

function Translations:social_party_kick()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.party.kick"] or "social.party.kick"
end

function Translations:social_party_leave()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.party.leave"] or "social.party.leave"
end

function Translations:social_party_promote()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["social.party.promote"] or "social.party.promote"
end

function Translations:ui_buttons_apply()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.apply"] or "ui.buttons.apply"
end

function Translations:ui_buttons_back()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.back"] or "ui.buttons.back"
end

function Translations:ui_buttons_buy()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.buy"] or "ui.buttons.buy"
end

function Translations:ui_buttons_cancel()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.cancel"] or "ui.buttons.cancel"
end

function Translations:ui_buttons_close()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.close"] or "ui.buttons.close"
end

function Translations:ui_buttons_confirm()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.confirm"] or "ui.buttons.confirm"
end

function Translations:ui_buttons_create()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.create"] or "ui.buttons.create"
end

function Translations:ui_buttons_delete()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.delete"] or "ui.buttons.delete"
end

function Translations:ui_buttons_edit()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.edit"] or "ui.buttons.edit"
end

function Translations:ui_buttons_load()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.load"] or "ui.buttons.load"
end

function Translations:ui_buttons_next()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.next"] or "ui.buttons.next"
end

function Translations:ui_buttons_reset()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.reset"] or "ui.buttons.reset"
end

function Translations:ui_buttons_save()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.save"] or "ui.buttons.save"
end

function Translations:ui_buttons_sell()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.sell"] or "ui.buttons.sell"
end

function Translations:ui_buttons_submit()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.submit"] or "ui.buttons.submit"
end

function Translations:ui_labels_coins()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.labels.coins"] or "ui.labels.coins"
end

function Translations:ui_labels_displayName()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.labels.displayName"] or "ui.labels.displayName"
end

function Translations:ui_labels_experience()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.labels.experience"] or "ui.labels.experience"
end

function Translations:ui_labels_gems()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.labels.gems"] or "ui.labels.gems"
end

function Translations:ui_labels_health()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.labels.health"] or "ui.labels.health"
end

function Translations:ui_labels_level()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.labels.level"] or "ui.labels.level"
end

function Translations:ui_labels_mana()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.labels.mana"] or "ui.labels.mana"
end

function Translations:ui_labels_player()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.labels.player"] or "ui.labels.player"
end

function Translations:ui_labels_robux()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.labels.robux"] or "ui.labels.robux"
end

function Translations:ui_labels_stamina()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.labels.stamina"] or "ui.labels.stamina"
end

function Translations:ui_labels_welcome()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.labels.welcome"] or "ui.labels.welcome"
end

function Translations:ui_messages_error()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.messages.error"] or "ui.messages.error"
end

function Translations:ui_messages_greeting(params)
    params = params or {}
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["ui.messages.greeting"] or "ui.messages.greeting"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:ui_messages_itemCount(params)
    params = params or {}
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["ui.messages.itemCount"] or "ui.messages.itemCount"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:ui_messages_loading()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.messages.loading"] or "ui.messages.loading"
end

function Translations:ui_messages_playerJoined(params)
    params = params or {}
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["ui.messages.playerJoined"] or "ui.messages.playerJoined"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:ui_messages_playerLeft(params)
    params = params or {}
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["ui.messages.playerLeft"] or "ui.messages.playerLeft"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:ui_messages_price(params)
    params = params or {}
    params.price = string.format("%.2f", tonumber(params.price) or 0)
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["ui.messages.price"] or "ui.messages.price"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:ui_messages_saving()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.messages.saving"] or "ui.messages.saving"
end

function Translations:ui_messages_score(params)
    params = params or {}
    params.score = math.floor(tonumber(params.score) or 0)
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local template = locale_data["ui.messages.score"] or "ui.messages.score"
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

function Translations:ui_messages_success()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.messages.success"] or "ui.messages.success"
end

function Translations:ui_messages_warning()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.messages.warning"] or "ui.messages.warning"
end

function Translations:ui_tooltips_buyItem()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.tooltips.buyItem"] or "ui.tooltips.buyItem"
end

function Translations:ui_tooltips_equipItem()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.tooltips.equipItem"] or "ui.tooltips.equipItem"
end

function Translations:ui_tooltips_sellItem()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.tooltips.sellItem"] or "ui.tooltips.sellItem"
end

function Translations:ui_tooltips_unequipItem()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.tooltips.unequipItem"] or "ui.tooltips.unequipItem"
end

function Translations:ui_tooltips_upgradeItem()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.tooltips.upgradeItem"] or "ui.tooltips.upgradeItem"
end

function Translations:ui_messages_items(count, params)
    params = params or {}
    params.count = count
    
    -- Determine plural category
    local category = "other"
    
    if self._locale == "en" then
        if count == 1 then
            category = "one"
        end
    elseif self._locale == "ru" or self._locale == "uk" then
        local mod10 = math.abs(count) % 10
        local mod100 = math.abs(count) % 100
        if mod10 == 1 and mod100 ~= 11 then
            category = "one"
        elseif mod10 >= 2 and mod10 <= 4 and (mod100 < 12 or mod100 > 14) then
            category = "few"
        else
            category = "many"
        end
    elseif self._locale == "ar" then
        local absCount = math.abs(count)
        local mod100 = absCount % 100
        if absCount == 0 then
            category = "zero"
        elseif absCount == 1 then
            category = "one"
        elseif absCount == 2 then
            category = "two"
        elseif mod100 >= 3 and mod100 <= 10 then
            category = "few"
        elseif mod100 >= 11 and mod100 <= 99 then
            category = "many"
        end
    end
    
    -- Get translation from embedded data
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    local key = "ui.messages.items(" .. category .. ")"
    local template = locale_data[key]
    
    -- Fallback to 'other' category if specific category not found
    if not template then
        template = locale_data["ui.messages.items(other)"] or key
    end
    local result = template
    for paramKey, value in pairs(params) do
        result = result:gsub("{" .. paramKey .. "}", tostring(value))
    end
    
    return result
end

Translations.game = {}
Translations.game.menu = {}
Translations.game.modes = {}
Translations.game.notifications = {}
Translations.game.status = {}
Translations.inventory = {}
Translations.inventory.actions = {}
Translations.inventory.info = {}
Translations.inventory.tabs = {}
Translations.settings = {}
Translations.settings.categories = {}
Translations.settings.options = {}
Translations.shop = {}
Translations.shop.actions = {}
Translations.shop.categories = {}
Translations.shop.messages = {}
Translations.social = {}
Translations.social.chat = {}
Translations.social.friends = {}
Translations.social.party = {}
Translations.ui = {}
Translations.ui.buttons = {}
Translations.ui.labels = {}
Translations.ui.messages = {}
Translations.ui.tooltips = {}

function Translations.game.menu:about()
    return self:game_menu_about()
end

function Translations.game.menu:achievements()
    return self:game_menu_achievements()
end

function Translations.game.menu:credits()
    return self:game_menu_credits()
end

function Translations.game.menu:friends()
    return self:game_menu_friends()
end

function Translations.game.menu:help()
    return self:game_menu_help()
end

function Translations.game.menu:leaderboard()
    return self:game_menu_leaderboard()
end

function Translations.game.menu:play()
    return self:game_menu_play()
end

function Translations.game.menu:profile()
    return self:game_menu_profile()
end

function Translations.game.menu:quit()
    return self:game_menu_quit()
end

function Translations.game.menu:settings()
    return self:game_menu_settings()
end

function Translations.game.modes:arena()
    return self:game_modes_arena()
end

function Translations.game.modes:campaign()
    return self:game_modes_campaign()
end

function Translations.game.modes:coop()
    return self:game_modes_coop()
end

function Translations.game.modes:multiplayer()
    return self:game_modes_multiplayer()
end

function Translations.game.modes:practice()
    return self:game_modes_practice()
end

function Translations.game.modes:raid()
    return self:game_modes_raid()
end

function Translations.game.modes:singleplayer()
    return self:game_modes_singleplayer()
end

function Translations.game.modes:survival()
    return self:game_modes_survival()
end

function Translations.game.modes:tutorial()
    return self:game_modes_tutorial()
end

function Translations.game.modes:versus()
    return self:game_modes_versus()
end

function Translations.game.notifications.achievementUnlocked(self, params)
    return self:game_notifications_achievementUnlocked(params)
end

function Translations.game.notifications.friendRequest(self, params)
    return self:game_notifications_friendRequest(params)
end

function Translations.game.notifications.levelUp(self, params)
    return self:game_notifications_levelUp(params)
end

function Translations.game.notifications.partyInvite(self, params)
    return self:game_notifications_partyInvite(params)
end

function Translations.game.notifications.questComplete(self, params)
    return self:game_notifications_questComplete(params)
end

function Translations.game.notifications.tradeRequest(self, params)
    return self:game_notifications_tradeRequest(params)
end

function Translations.game.status:away()
    return self:game_status_away()
end

function Translations.game.status:busy()
    return self:game_status_busy()
end

function Translations.game.status:connected()
    return self:game_status_connected()
end

function Translations.game.status:connecting()
    return self:game_status_connecting()
end

function Translations.game.status:disconnected()
    return self:game_status_disconnected()
end

function Translations.game.status:inGame()
    return self:game_status_inGame()
end

function Translations.game.status:inLobby()
    return self:game_status_inLobby()
end

function Translations.game.status:offline()
    return self:game_status_offline()
end

function Translations.game.status:online()
    return self:game_status_online()
end

function Translations.game.status:searching()
    return self:game_status_searching()
end

function Translations.inventory.actions:destroy()
    return self:inventory_actions_destroy()
end

function Translations.inventory.actions:drop()
    return self:inventory_actions_drop()
end

function Translations.inventory.actions:enchant()
    return self:inventory_actions_enchant()
end

function Translations.inventory.actions:equip()
    return self:inventory_actions_equip()
end

function Translations.inventory.actions:gift()
    return self:inventory_actions_gift()
end

function Translations.inventory.actions:repair()
    return self:inventory_actions_repair()
end

function Translations.inventory.actions:trade()
    return self:inventory_actions_trade()
end

function Translations.inventory.actions:unequip()
    return self:inventory_actions_unequip()
end

function Translations.inventory.actions:upgrade()
    return self:inventory_actions_upgrade()
end

function Translations.inventory.actions:use()
    return self:inventory_actions_use()
end

function Translations.inventory.info.damage(self, params)
    return self:inventory_info_damage(params)
end

function Translations.inventory.info.defense(self, params)
    return self:inventory_info_defense(params)
end

function Translations.inventory.info.durability(self, params)
    return self:inventory_info_durability(params)
end

function Translations.inventory.info.quantity(self, params)
    return self:inventory_info_quantity(params)
end

function Translations.inventory.info.rarity(self, params)
    return self:inventory_info_rarity(params)
end

function Translations.inventory.info.weight(self, params)
    return self:inventory_info_weight(params)
end

function Translations.inventory.tabs:all()
    return self:inventory_tabs_all()
end

function Translations.inventory.tabs:armor()
    return self:inventory_tabs_armor()
end

function Translations.inventory.tabs:consumables()
    return self:inventory_tabs_consumables()
end

function Translations.inventory.tabs:materials()
    return self:inventory_tabs_materials()
end

function Translations.inventory.tabs:pets()
    return self:inventory_tabs_pets()
end

function Translations.inventory.tabs:quest()
    return self:inventory_tabs_quest()
end

function Translations.inventory.tabs:vehicles()
    return self:inventory_tabs_vehicles()
end

function Translations.inventory.tabs:weapons()
    return self:inventory_tabs_weapons()
end

function Translations.settings.categories:accessibility()
    return self:settings_categories_accessibility()
end

function Translations.settings.categories:audio()
    return self:settings_categories_audio()
end

function Translations.settings.categories:controls()
    return self:settings_categories_controls()
end

function Translations.settings.categories:gameplay()
    return self:settings_categories_gameplay()
end

function Translations.settings.categories:general()
    return self:settings_categories_general()
end

function Translations.settings.categories:graphics()
    return self:settings_categories_graphics()
end

function Translations.settings.options:brightness()
    return self:settings_options_brightness()
end

function Translations.settings.options:fov()
    return self:settings_options_fov()
end

function Translations.settings.options:fullscreen()
    return self:settings_options_fullscreen()
end

function Translations.settings.options:invertY()
    return self:settings_options_invertY()
end

function Translations.settings.options:language()
    return self:settings_options_language()
end

function Translations.settings.options:mouseSensitivity()
    return self:settings_options_mouseSensitivity()
end

function Translations.settings.options:musicVolume()
    return self:settings_options_musicVolume()
end

function Translations.settings.options:particles()
    return self:settings_options_particles()
end

function Translations.settings.options:quality()
    return self:settings_options_quality()
end

function Translations.settings.options:sfxVolume()
    return self:settings_options_sfxVolume()
end

function Translations.settings.options:shadows()
    return self:settings_options_shadows()
end

function Translations.settings.options:volume()
    return self:settings_options_volume()
end

function Translations.settings.options:vsync()
    return self:settings_options_vsync()
end

function Translations.shop.actions:addToCart()
    return self:shop_actions_addToCart()
end

function Translations.shop.actions:checkout()
    return self:shop_actions_checkout()
end

function Translations.shop.actions:clearCart()
    return self:shop_actions_clearCart()
end

function Translations.shop.actions:compare()
    return self:shop_actions_compare()
end

function Translations.shop.actions:preview()
    return self:shop_actions_preview()
end

function Translations.shop.actions:purchase()
    return self:shop_actions_purchase()
end

function Translations.shop.actions:removeFromCart()
    return self:shop_actions_removeFromCart()
end

function Translations.shop.actions:viewCart()
    return self:shop_actions_viewCart()
end

function Translations.shop.categories:accessories()
    return self:shop_categories_accessories()
end

function Translations.shop.categories:armor()
    return self:shop_categories_armor()
end

function Translations.shop.categories:bundles()
    return self:shop_categories_bundles()
end

function Translations.shop.categories:consumables()
    return self:shop_categories_consumables()
end

function Translations.shop.categories:emotes()
    return self:shop_categories_emotes()
end

function Translations.shop.categories:equipment()
    return self:shop_categories_equipment()
end

function Translations.shop.categories:featured()
    return self:shop_categories_featured()
end

function Translations.shop.categories:gamepasses()
    return self:shop_categories_gamepasses()
end

function Translations.shop.categories:materials()
    return self:shop_categories_materials()
end

function Translations.shop.categories:pets()
    return self:shop_categories_pets()
end

function Translations.shop.categories:potions()
    return self:shop_categories_potions()
end

function Translations.shop.categories:vehicles()
    return self:shop_categories_vehicles()
end

function Translations.shop.categories:weapons()
    return self:shop_categories_weapons()
end

function Translations.shop.messages:cartEmpty()
    return self:shop_messages_cartEmpty()
end

function Translations.shop.messages:insufficientFunds()
    return self:shop_messages_insufficientFunds()
end

function Translations.shop.messages:insufficientRobux()
    return self:shop_messages_insufficientRobux()
end

function Translations.shop.messages:itemAdded()
    return self:shop_messages_itemAdded()
end

function Translations.shop.messages:itemRemoved()
    return self:shop_messages_itemRemoved()
end

function Translations.shop.messages:purchaseFailed()
    return self:shop_messages_purchaseFailed()
end

function Translations.shop.messages:purchaseSuccess()
    return self:shop_messages_purchaseSuccess()
end

function Translations.shop.messages.requiresGamepass(self, params)
    return self:shop_messages_requiresGamepass(params)
end

function Translations.social.chat:globalChat()
    return self:social_chat_globalChat()
end

function Translations.social.chat:mute()
    return self:social_chat_mute()
end

function Translations.social.chat:report()
    return self:social_chat_report()
end

function Translations.social.chat:send()
    return self:social_chat_send()
end

function Translations.social.chat:teamChat()
    return self:social_chat_teamChat()
end

function Translations.social.chat:unmute()
    return self:social_chat_unmute()
end

function Translations.social.chat:whisper()
    return self:social_chat_whisper()
end

function Translations.social.friends:add()
    return self:social_friends_add()
end

function Translations.social.friends:block()
    return self:social_friends_block()
end

function Translations.social.friends:invite()
    return self:social_friends_invite()
end

function Translations.social.friends:offline()
    return self:social_friends_offline()
end

function Translations.social.friends:online()
    return self:social_friends_online()
end

function Translations.social.friends:remove()
    return self:social_friends_remove()
end

function Translations.social.friends:requests()
    return self:social_friends_requests()
end

function Translations.social.friends:unblock()
    return self:social_friends_unblock()
end

function Translations.social.party:create()
    return self:social_party_create()
end

function Translations.social.party:invite()
    return self:social_party_invite()
end

function Translations.social.party:join()
    return self:social_party_join()
end

function Translations.social.party:kick()
    return self:social_party_kick()
end

function Translations.social.party:leave()
    return self:social_party_leave()
end

function Translations.social.party:promote()
    return self:social_party_promote()
end

function Translations.ui.buttons:apply()
    return self:ui_buttons_apply()
end

function Translations.ui.buttons:back()
    return self:ui_buttons_back()
end

function Translations.ui.buttons:buy()
    return self:ui_buttons_buy()
end

function Translations.ui.buttons:cancel()
    return self:ui_buttons_cancel()
end

function Translations.ui.buttons:close()
    return self:ui_buttons_close()
end

function Translations.ui.buttons:confirm()
    return self:ui_buttons_confirm()
end

function Translations.ui.buttons:create()
    return self:ui_buttons_create()
end

function Translations.ui.buttons:delete()
    return self:ui_buttons_delete()
end

function Translations.ui.buttons:edit()
    return self:ui_buttons_edit()
end

function Translations.ui.buttons:load()
    return self:ui_buttons_load()
end

function Translations.ui.buttons:next()
    return self:ui_buttons_next()
end

function Translations.ui.buttons:reset()
    return self:ui_buttons_reset()
end

function Translations.ui.buttons:save()
    return self:ui_buttons_save()
end

function Translations.ui.buttons:sell()
    return self:ui_buttons_sell()
end

function Translations.ui.buttons:submit()
    return self:ui_buttons_submit()
end

function Translations.ui.labels:coins()
    return self:ui_labels_coins()
end

function Translations.ui.labels:displayName()
    return self:ui_labels_displayName()
end

function Translations.ui.labels:experience()
    return self:ui_labels_experience()
end

function Translations.ui.labels:gems()
    return self:ui_labels_gems()
end

function Translations.ui.labels:health()
    return self:ui_labels_health()
end

function Translations.ui.labels:level()
    return self:ui_labels_level()
end

function Translations.ui.labels:mana()
    return self:ui_labels_mana()
end

function Translations.ui.labels:player()
    return self:ui_labels_player()
end

function Translations.ui.labels:robux()
    return self:ui_labels_robux()
end

function Translations.ui.labels:stamina()
    return self:ui_labels_stamina()
end

function Translations.ui.labels:welcome()
    return self:ui_labels_welcome()
end

function Translations.ui.messages:error()
    return self:ui_messages_error()
end

function Translations.ui.messages.greeting(self, params)
    return self:ui_messages_greeting(params)
end

function Translations.ui.messages.itemCount(self, params)
    return self:ui_messages_itemCount(params)
end

function Translations.ui.messages:loading()
    return self:ui_messages_loading()
end

function Translations.ui.messages.playerJoined(self, params)
    return self:ui_messages_playerJoined(params)
end

function Translations.ui.messages.playerLeft(self, params)
    return self:ui_messages_playerLeft(params)
end

function Translations.ui.messages.price(self, params)
    return self:ui_messages_price(params)
end

function Translations.ui.messages:saving()
    return self:ui_messages_saving()
end

function Translations.ui.messages.score(self, params)
    return self:ui_messages_score(params)
end

function Translations.ui.messages:success()
    return self:ui_messages_success()
end

function Translations.ui.messages:warning()
    return self:ui_messages_warning()
end

function Translations.ui.tooltips:buyItem()
    return self:ui_tooltips_buyItem()
end

function Translations.ui.tooltips:equipItem()
    return self:ui_tooltips_equipItem()
end

function Translations.ui.tooltips:sellItem()
    return self:ui_tooltips_sellItem()
end

function Translations.ui.tooltips:unequipItem()
    return self:ui_tooltips_unequipItem()
end

function Translations.ui.tooltips:upgradeItem()
    return self:ui_tooltips_upgradeItem()
end

function Translations.ui.messages:items(count, params)
    return self:ui_messages_items(count, params)
end


return Translations
