--[[
    Roblox Slang - Type-Safe Internationalization
    
    This file is auto-generated by roblox-slang CLI tool.
    DO NOT MODIFY BY HAND - Your changes will be overwritten!
    
    Generated from translation files in your project.
    To update translations, edit your JSON/YAML files and run:
        roblox-slang build
    
    Learn more: https://github.com/mathtechstudio/roblox-slang
--]]

-- Embedded translation data (generated at build time)
local EMBEDDED_TRANSLATIONS = {
    ["en"] = {
        ["ui.buttons.buy"] = "Buy",
        ["ui.buttons.cancel"] = "Cancel",
        ["ui.buttons.sell"] = "Sell",
        ["ui.labels.welcome"] = "Welcome to the game!",
    },
}

local Translations = {}
Translations.__index = Translations

--- Create a new Translations instance
--- @param locale string The locale to use (e.g., "en", "id")
--- @return Translations
function Translations.new(locale)
    local self = setmetatable({}, Translations)
    self._locale = locale or "en"
    self._localeChangedCallbacks = {}
    
    -- Try to get LocalizationService translator (optional)
    local LocalizationService = game:GetService("LocalizationService")
    local success, translator = pcall(function()
        return LocalizationService:GetTranslatorForLocaleAsync(self._locale)
    end)
    
    if success then
        self._translator = translator
    else
        warn("LocalizationService unavailable, using embedded translations")
        self._translator = nil
    end
    
    return self
end

--- Switch to a different locale
--- @param locale string The new locale to use
function Translations:setLocale(locale)
    if self._locale == locale then
        return
    end
    
    local oldLocale = self._locale
    self._locale = locale
    
    -- Try to get new translator
    local LocalizationService = game:GetService("LocalizationService")
    local success, translator = pcall(function()
        return LocalizationService:GetTranslatorForLocaleAsync(locale)
    end)
    
    if success then
        self._translator = translator
    else
        self._translator = nil
    end
    
    -- Fire locale changed callbacks
    for _, callback in ipairs(self._localeChangedCallbacks) do
        task.spawn(callback, locale, oldLocale)
    end
end

--- Get current locale
--- @return string
function Translations:getLocale()
    return self._locale
end

--- Register a callback for locale changes
--- @param callback function(newLocale: string, oldLocale: string)
function Translations:onLocaleChanged(callback)
    table.insert(self._localeChangedCallbacks, callback)
end

--- Detect player's locale based on their country
--- @param player Player The player to detect locale for
--- @return string The detected locale code
function Translations.detectLocale(player)
    local LocalizationService = game:GetService("LocalizationService")
    
    -- Try to get player's country
    local success, countryCode = pcall(function()
        return LocalizationService:GetCountryRegionForPlayerAsync(player)
    end)
    
    if not success or not countryCode then
        return "en"  -- Fallback to English
    end
    
    -- Map country code to locale
    local countryLocaleMap = {
        ["US"] = "en",
        ["GB"] = "en",
        ["CA"] = "en",
        ["AU"] = "en",
        ["NZ"] = "en",
        ["IE"] = "en",
        ["ZA"] = "en",
        ["SG"] = "en",
        ["PH"] = "en",
        ["ES"] = "es",
        ["MX"] = "es",
        ["AR"] = "es",
        ["CO"] = "es",
        ["CL"] = "es",
        ["PE"] = "es",
        ["VE"] = "es",
        ["EC"] = "es",
        ["GT"] = "es",
        ["CU"] = "es",
        ["BO"] = "es",
        ["DO"] = "es",
        ["HN"] = "es",
        ["PY"] = "es",
        ["SV"] = "es",
        ["NI"] = "es",
        ["CR"] = "es",
        ["PA"] = "es",
        ["UY"] = "es",
        ["FR"] = "fr",
        ["BE"] = "fr",
        ["CH"] = "fr",
        ["LU"] = "fr",
        ["MC"] = "fr",
        ["DE"] = "de",
        ["AT"] = "de",
        ["LI"] = "de",
        ["PT"] = "pt",
        ["BR"] = "pt",
        ["AO"] = "pt",
        ["MZ"] = "pt",
        ["ID"] = "id",
        ["IT"] = "it",
        ["SM"] = "it",
        ["VA"] = "it",
        ["JP"] = "ja",
        ["KR"] = "ko",
        ["RU"] = "ru",
        ["BY"] = "ru",
        ["KZ"] = "ru",
        ["TH"] = "th",
        ["TR"] = "tr",
        ["VN"] = "vi",
        ["PL"] = "pl",
        ["CN"] = "zh-cn",
        ["TW"] = "zh-tw",
        ["HK"] = "zh-tw",
        ["MO"] = "zh-tw",
        ["UA"] = "uk",
    }
    
    return countryLocaleMap[countryCode] or "en"
end

--- Create a new Translations instance for a player (auto-detect locale)
--- @param player Player The player to create translations for
--- @return Translations
function Translations.newForPlayer(player)
    local locale = Translations.detectLocale(player)
    return Translations.new(locale)
end

-- Internal methods (flat keys)

function Translations:ui_buttons_buy()
    if self._translator then
        local success, result = pcall(function()
            return self._translator:FormatByKey("ui.buttons.buy")
        end)
        if success and result ~= "" then
            return result
        end
    end
    
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.buy"] or "ui.buttons.buy"
end

function Translations:ui_buttons_cancel()
    if self._translator then
        local success, result = pcall(function()
            return self._translator:FormatByKey("ui.buttons.cancel")
        end)
        if success and result ~= "" then
            return result
        end
    end
    
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.cancel"] or "ui.buttons.cancel"
end

function Translations:ui_buttons_sell()
    if self._translator then
        local success, result = pcall(function()
            return self._translator:FormatByKey("ui.buttons.sell")
        end)
        if success and result ~= "" then
            return result
        end
    end
    
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.sell"] or "ui.buttons.sell"
end

function Translations:ui_labels_welcome()
    if self._translator then
        local success, result = pcall(function()
            return self._translator:FormatByKey("ui.labels.welcome")
        end)
        if success and result ~= "" then
            return result
        end
    end
    
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.labels.welcome"] or "ui.labels.welcome"
end

-- Namespace structure (syntax sugar)

Translations.ui = {}
Translations.ui.buttons = {}
Translations.ui.labels = {}

function Translations.ui.buttons.buy(self)
    return self:ui_buttons_buy()
end

function Translations.ui.buttons.cancel(self)
    return self:ui_buttons_cancel()
end

function Translations.ui.buttons.sell(self)
    return self:ui_buttons_sell()
end

function Translations.ui.labels.welcome(self)
    return self:ui_labels_welcome()
end


return Translations
