--[[
    Roblox Slang - Type-Safe Internationalization
    
    This file is auto-generated by roblox-slang CLI tool.
    DO NOT MODIFY BY HAND - Your changes will be overwritten!
    
    Generated from translation files in your project.
    To update translations, edit your JSON/YAML files and run:
        roblox-slang build
    
    Learn more: https://github.com/mathtechstudio/roblox-slang
--]]

-- Embedded translation data (generated at build time)
local EMBEDDED_TRANSLATIONS = {
    ["en"] = {
        ["ui.buttons.buy"] = "Buy",
        ["ui.buttons.cancel"] = "Cancel",
        ["ui.buttons.sell"] = "Sell",
        ["ui.labels.welcome"] = "Welcome to the game!",
    },
}

local Translations = {}
Translations.__index = Translations

--- Create a new Translations instance
--- @param locale string The locale to use (e.g., "en", "id")
--- @return Translations
function Translations.new(locale)
    local self = setmetatable({}, Translations)
    self._locale = locale or "en"
    self._localeChangedCallbacks = {}
    
    return self
end

--- Switch to a different locale
--- @param locale string The new locale to use
function Translations:setLocale(locale)
    if self._locale == locale then
        return
    end
    
    local oldLocale = self._locale
    self._locale = locale
    
    -- Fire locale changed callbacks
    for _, callback in ipairs(self._localeChangedCallbacks) do
        task.spawn(callback, locale, oldLocale)
    end
end

--- Get current locale
--- @return string
function Translations:getLocale()
    return self._locale
end

--- Register a callback for locale changes
--- @param callback function(newLocale: string, oldLocale: string)
function Translations:onLocaleChanged(callback)
    table.insert(self._localeChangedCallbacks, callback)
end

-- Internal methods (flat keys)

function Translations:ui_buttons_buy()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.buy"] or "ui.buttons.buy"
end

function Translations:ui_buttons_cancel()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.cancel"] or "ui.buttons.cancel"
end

function Translations:ui_buttons_sell()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.buttons.sell"] or "ui.buttons.sell"
end

function Translations:ui_labels_welcome()
    local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
    return locale_data["ui.labels.welcome"] or "ui.labels.welcome"
end

-- Namespace structure (syntax sugar)

Translations.ui = {}
Translations.ui.buttons = {}
Translations.ui.labels = {}

function Translations.ui.buttons.buy(self)
    return self:ui_buttons_buy()
end

function Translations.ui.buttons.cancel(self)
    return self:ui_buttons_cancel()
end

function Translations.ui.buttons.sell(self)
    return self:ui_buttons_sell()
end

function Translations.ui.labels.welcome(self)
    return self:ui_labels_welcome()
end


return Translations
