-- Generated by roblox-slang. DO NOT MODIFY BY HAND!

local EMBEDDED_TRANSLATIONS = {
	["en"] = {
		["ui.buttons.buy"] = "Buy",
		["ui.buttons.cancel"] = "Cancel",
		["ui.buttons.sell"] = "Sell",
		["ui.labels.welcome"] = "Welcome to the game!",
	},
}

local Translations = {}
Translations.__index = Translations

function Translations.new(locale)
	local self = setmetatable({}, Translations)
	self._locale = locale or "en"
	self._localeChangedCallbacks = {}

	Translations._setupNamespaces(self)
	return self
end

function Translations:setLocale(locale)
	if self._locale == locale then
		return
	end

	local oldLocale = self._locale
	self._locale = locale

	for _, callback in ipairs(self._localeChangedCallbacks) do
		task.spawn(callback, locale, oldLocale)
	end
end

function Translations:getLocale()
	return self._locale
end

function Translations:onLocaleChanged(callback)
	table.insert(self._localeChangedCallbacks, callback)
end

function Translations.detectLocale(player)
	local localeId = player.LocaleId
	if not localeId or localeId == "" then
		return "en"
	end

	local normalized = string.lower(localeId):gsub("_", "-")
	local baseCode = string.match(normalized, "^(%w+)")
	if baseCode == "zh" then
		return normalized
	end
	return baseCode or "en"
end

function Translations.newForPlayer(player)
	local locale = Translations.detectLocale(player)
	return Translations.new(locale)
end

function Translations:ui_buttons_buy()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.buy"] or "ui.buttons.buy"
end

function Translations:ui_buttons_cancel()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.cancel"] or "ui.buttons.cancel"
end

function Translations:ui_buttons_sell()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.buttons.sell"] or "ui.buttons.sell"
end

function Translations:ui_labels_welcome()
	local locale_data = EMBEDDED_TRANSLATIONS[self._locale] or EMBEDDED_TRANSLATIONS["en"]
	return locale_data["ui.labels.welcome"] or "ui.labels.welcome"
end

function Translations._setupNamespaces(self)
	self.ui = {}
	self.ui.buttons = {}
	self.ui.labels = {}

	self.ui.buttons.buy = function()
		return self:ui_buttons_buy()
	end
	self.ui.buttons.cancel = function()
		return self:ui_buttons_cancel()
	end
	self.ui.buttons.sell = function()
		return self:ui_buttons_sell()
	end
	self.ui.labels.welcome = function()
		return self:ui_labels_welcome()
	end
end

return Translations
